version: "3"

services:
#  app:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    command: ./bbcar
#    volumes:
#      - ./logs/:/logs
#    ports:
#      - 2112:2112
#    networks:
#      - local
#    depends_on:
#      - postgres

  postgres:
    image: "postgres:11.2"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - local
