version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./transfer
    ports:
      - 5580:5580
    networks:
      - local
    depends_on:
      - postgres

  migrate:
    image: migrate/migrate
    restart: on-failure:5
    volumes:
        - ./psql/migrations:/migrations
    command: -path /migrations -database postgres://postgres:5432/transfer?user=postgres&password=secret&sslmode=disable up
    depends_on:
      - postgres
    networks:
      - local

  postgres:
    image: "postgres:11.2"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: transfer
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - local

volumes:
  postgres_storage:

networks:
  local:
    driver: bridge
